# Todo before deploy this services:
# - Map host port to traefik docker compose file
# - Create new entrypoint inside traefik static config called tcpport

version: "3.9"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - public-net
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.tcp.routers.mongodb.rule=HostSNI(`mongodb.domain.tld`)
        - traefik.tcp.routers.mongodb.entrypoints=tcpport
        - traefik.tcp.routers.mongodb.tls=true
        - traefik.tcp.services.mongodb.loadbalancer.server.port=27017

networks:
  public-net:
    external: true
