version: "3.0"

networks:
  proxy:
    name: proxy
    external: false

services:
  proxy:
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
    restart: on-failure
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.proxy.rule=Host(`traefik.example.com`)"
      - "traefik.http.routers.proxy.entrypoints=http"
      - "traefik.http.routers.proxy.service=api@internal"
    networks:
      - proxy
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
       - ./configurations/:/rules
    command:
      - --global.sendAnonymousUsage=true
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
      - --api=false
      - --api.insecure=false
      - --api.dashboard=true
      - --serversTransport.insecureSkipVerify=true
      - --log=true
      - --log.filePath=/logs/traefik.log
      - --log.level=DEBUG # DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=true
      - --accessLog.filePath=/logs/access.log
      - --accessLog.filters.statusCodes=204-299,400-499,500-599
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedByDefault=false
      # Add dns-cloudflare as default certresolver for all services. Also enables TLS and no need to specify on individual services
      - --entrypoints.https.http.tls.certresolver=dns-cloudflare
      - --entrypoints.https.http.tls.domains[0].main=$DOMAIN_NAME
      - --entrypoints.https.http.tls.domains[0].sans=*.$DOMAIN_NAME
      - --providers.docker.network=proxy
      #- --providers.docker.swarmMode=false
      - --providers.file.directory=/rules # Load dynamic configuration from one or more .toml or .yml files in a directory
      #- --providers.file.filename=/path/to/file # Load dynamic configuration from a file
      - --providers.file.watch=true
      #- --certificatesResolvers.dns-cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory # LetsEncrypt Staging Server - uncomment when testing
      - --certificatesResolvers.dns-cloudflare.acme.email=$CLOUDFLARE_EMAIL
      - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.delayBeforeCheck=90 # To delay DNS check and reduce LE hitrate


  whoami:
    image: traefik/whoami:latest
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`whoami.example.com`)"
      - "traefik.http.routers.dashboard.entrypoints=http"
      - "traefik.http.services.dashboard.loadbalancer.server.port=3000"

